# Generated by Django 4.1.6 on 2023-02-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=500)),
                ('passout_date', models.DateField()),
            ],
        ),
    ]
