# Generated by Django 4.1.6 on 2023-02-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
